### ISSUE TITLE
Build Failed when trying build a source distribution

### ISSUE THREAD

**Issue by hashimoh** [eb4j/ebviewer#23]
While building, I encounter following messages and build failed.
An exception occurred applying plugin request [id: 'com.palantir.git-version', version: '0.12.3']
> Failed to apply plugin 'com.palantir.git-version'.
   > Cannot find '.git' directory

**Comment by miurahr** [comment]
Current application depends on git versioning system.
Please git clone the repository to your local.

**Comment by miurahr** [comment]
I've updated a description of build from source section on README.

**Comment by miurahr** [comment]
This seems known issue on git-version plugin
 https://github.com/palantir/gradle-git-version/issues/327

I'd like to watch it.

**Comment by miurahr** [comment]
I found a way to do work around of it.

**Comment by miurahr** [comment]
Now v0.6.0 provide source package and support building from it.
