### ISSUE TITLE
Feature: Add support for MDict dictionary format (MDD and MDX)

### ISSUE THREAD

**Issue by shawkynasr** [eb4j/ebviewer#38]
Hi Hiroshi,
    You did great job to support many common extensions, I suggest supporting mdx.

You can check [ *.mdx/*.mdd interpreter js implements ](https://github.com/terasum/js-mdict)

Kind regards,

**Comment by miurahr** [comment]
There may be references to see

- https://github.com/zhansliu/writemdict/blob/master/fileformat.md
- https://bitbucket.org/xwang/mdict-analysis/src
- https://pypi.org/project/mdict-utils/
- https://github.com/KnIfER/mdict-java

**Comment by miurahr** [comment]
It seems there is no **good** java library shared on Maven Central / OSSRH,  compatible with GPL.

**Comment by shawkynasr** [comment]
GPL there are python library

**Comment by miurahr** [comment]
I've just started to implement parser. https://github.com/eb4j/mdict4j
@shawkynasr do you have a test mdx data that is ok for distributing as a part of OSS project?

**Comment by miurahr** [comment]
@shawkynasr does #38 works for you?
It is very experimental support for MDX file.

**Comment by miurahr** [comment]
Here is capture of #64 running test.
![ebviewer_mdict_image](https://user-images.githubusercontent.com/123720/142353347-ab54ddaf-eaec-4090-95ce-39a97cfe8078.png)

**Comment by miurahr** [comment]
Now mdict support is released as v0.7.0. @shawkynasr could you try?

**Comment by miurahr** [comment]
Out v0.7.1 with mdict media(sound/image) support.

**Comment by shawkynasr** [comment]
Many thanks!

There are other point CSS with mdd
